In [297]:
import numpy as np

In [298]:
#1
df = np.loadtxt("artificial1d.csv", delimiter= ",", skiprows= 1)

In [299]:
#2
np.random.seed(3)
np.random.shuffle(df)

In [300]:
#3
X = df[:,[0]]
y = df[:,[1]]

In [301]:
#4
var_pol = np.c_[X, X**2, X**3, X**4]
print (var_pol.shape)

(29, 4)


In [302]:
#5
X_treino = var_pol[:20]
X_teste = var_pol[20:]
y_treino = y[:20]
y_teste = y[20:]

In [303]:
#6
def regressao (var_pol, y, L):

    X1 = np.c_[np.ones(var_pol.shape[0]), var_pol]
    l = np.eye(X1.shape[1])
    l[0,0] = 0
    L_ = l * L
    w = (np.linalg.inv( (X1.T) @ X1+L_)) @ ((X1.T) @ y)

    return (w)

In [305]:
w = regressao(X_treino, y_treino, 0)
print (w)


[[ 0.18363881]
 [ 2.05620875]
 [-1.51168649]
 [-1.09727214]
 [ 2.35321567]]


In [306]:
w = regressao(X_teste, y_teste, 0)
print (w)

[[-0.42203003]
 [ 2.07458201]
 [ 2.76093075]
 [-1.13365733]
 [-2.72569091]]


In [307]:
def predict_multivariate(X,w):

    c1 = np.c_[np.ones(X.shape[0]), X]

    y_predict = c1 @ w

    return y_predict


In [308]:
y_predict = predict_multivariate(X_treino, w)
print (y_predict)

[[ 0.42855168]
 [ 0.21439763]
 [-0.60615286]
 [ 1.18656295]
 [-0.17943904]
 [ 0.00951049]
 [-0.49024179]
 [-0.84361614]
 [-0.93773004]
 [ 1.30126282]
 [-0.34726014]
 [-0.7795105 ]
 [ 1.19262893]
 [-0.79465276]
 [-0.80514815]
 [-0.78290434]
 [ 0.85057861]
 [-0.79134868]
 [-0.69424204]
 [ 0.55413449]]


In [309]:
y_predict = predict_multivariate(X_teste, w)
print (y_predict)

[[ 0.64382213]
 [ 1.03771089]
 [-1.09342734]
 [-0.80626276]
 [ 0.93976438]
 [-0.79555867]
 [ 1.31599934]
 [ 1.34806282]
 [-0.75523785]]


In [ ]:
lambdas = (0, 0.001, 0.01, 0.1, 1, 10, 100)

for L in lambdas:
  print (L)

In [310]:
#7
def MSE_teste (y_teste, y_predict):
    mse_teste = np.mean ((y_teste - y_predict)**2)

    return mse_teste

def MAPE (y_teste, y_predict):
    mape = 100*(np.mean((y_teste - y_predict)/y_teste))

    return mape

def R2 (y_teste, y_predict):
    r2 = 1 - np.sum((y_teste - y_predict)**2) / np.sum((y_teste-(np.mean(y_teste)))**2)

    return r2

In [311]:
mse_teste = MSE_teste (y_teste, y_predict)
print ("MSE:", mse_teste)

MSE: 0.20869679032641936


In [312]:
mape = MAPE(y_teste, y_predict)
print ("MAPE:", mape)

MAPE: -18.129503202447136


In [313]:
r2 = R2 (y_teste, y_predict)
print ("R2:", r2)

R2: 0.8207202854922213
