In [585]:
import numpy as np

In [586]:
#1
df = np.loadtxt("artificial1d.csv", delimiter= ",", skiprows= 1)

In [587]:
#2
np.random.seed(3)
np.random.shuffle(df)

In [588]:
#3
X = df[:,[0]]
y = df[:,[1]]

In [589]:
#4
var_pol = np.c_[X, X**2, X**3, X**4]
print (var_pol.shape)

(29, 4)


In [590]:
X_treino = var_pol[:20]
X_teste = var_pol[20:]
y_treino = y[:20]
y_teste = y[20:]

In [591]:
def regressao (var_pol, y, L):

    X1 = np.c_[np.ones(var_pol.shape[0]), var_pol]
    l = np.eye(X1.shape[1])
    l[0,0] = 0
    L_ = l * L
    w = (np.linalg.inv( (X1.T) @ X1+L_)) @ ((X1.T) @ y)

    return (w)

In [592]:
w = regressao (X_treino, y_treino, 1)
print (w)

[[0.0683741 ]
 [1.17049678]
 [0.02815254]
 [0.31918887]
 [0.21613207]]


In [593]:
w = regressao (X_teste, y_teste, 1)
print (w)

[[ 0.01683063]
 [ 0.99641315]
 [ 0.12990617]
 [ 0.25774849]
 [-0.02543296]]


In [594]:
def predict_multivariate(X,w):
    
    c1 = np.c_[np.ones(X.shape[0]), X]
    
    y_predict = c1 @ w

    return y_predict


In [595]:
y_predict = predict_multivariate(X_treino, w)
print (y_predict)

[[ 0.34604238]
 [ 0.26845156]
 [-0.08514465]
 [ 1.12343107]
 [ 0.12158048]
 [ 0.19378621]
 [-0.01738458]
 [-0.83036175]
 [-0.92477972]
 [ 0.79321666]
 [ 0.0513547 ]
 [-0.65740309]
 [ 0.69449404]
 [-0.50128874]
 [-0.42797794]
 [-0.57755788]
 [ 0.51179478]
 [-0.28782943]
 [-0.15244658]
 [ 1.37546547]]


In [596]:
y_predict = predict_multivariate(X_teste, w)
print (y_predict)

[[ 0.42701071]
 [ 0.60081901]
 [-1.02538281]
 [-0.35702154]
 [ 1.24603601]
 [-0.74145593]
 [ 1.00732289]
 [ 0.89736988]
 [-0.21982528]]


In [597]:
def MSE_teste (y_teste, y_predict):
    mse_teste = np.mean ((y_teste - y_predict)**2)

    return mse_teste

def MAPE (y_teste, y_predict):
    mape = 100*(np.mean((y_teste - y_predict)/y_teste))

    return mape

def R2 (y_teste, y_predict):
    r2 = 1 - np.sum((y_teste - y_predict)**2) / np.sum((y_teste-(np.mean(y_teste)))**2)

    return r2

In [598]:
mse_teste = MSE_teste (y_teste, y_predict)
print ("MSE:", mse_teste)

MSE: 0.33382243113908605


In [599]:
mape = MAPE(y_teste, y_predict)
print ("MAPE:", mape)

MAPE: 9.502040023037866


In [600]:
r2 = R2 (y_teste, y_predict)
print ("R2:", r2)

R2: 0.7132318611258885
